"""Independent functional evidence checks for autonomous project benchmarks."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SOURCE_EXTENSIONS = {".c", ".cpp", ".cs", ".go", ".h", ".java", ".js", ".jsx", ".py", ".rs", ".ts", ".tsx"}
EXCLUDED_PARTS = {".git", ".next", "build", "dist", "node_modules", "outputs", "project_backups", "__pycache__"}
PLACEHOLDER_MARKERS = (
    "starter file generated by ann",
    "starter module generated by ann",
    "todo: implement",
    "not implemented",
    "placeholder implementation",
)


@dataclass(frozen=True)
class CapabilityContract:
    minimum_source_files: int
    minimum_meaningful_loc: int
    minimum_test_files: int
    required_command_kinds: tuple[str, ...]
    keyword_groups: tuple[tuple[str, ...], ...]
    requires_visual_evidence: bool = False


SAAS_COMMANDS = ("python_test", "node_test", "build", "e2e")
CONTRACTS: dict[str, CapabilityContract] = {
    "crm_saas_multitenant": CapabilityContract(
        8,
        300,
        3,
        SAAS_COMMANDS,
        (("tenant", "organization"), ("account", "contact"), ("deal", "pipeline"), ("role", "permission"), ("jwt", "auth")),
        True,
    ),
    "ecommerce_marketplace": CapabilityContract(
        8,
        300,
        3,
        SAAS_COMMANDS,
        (("product", "catalog"), ("cart", "basket"), ("order", "checkout"), ("seller", "vendor"), ("payment", "billing")),
        True,
    ),
    "booking_platform": CapabilityContract(
        8,
        300,
        3,
        SAAS_COMMANDS,
        (("booking", "appointment"), ("availability", "calendar"), ("customer", "user"), ("timezone", "schedule"), ("jwt", "auth")),
        True,
    ),
    "lms_platform": CapabilityContract(
        8,
        300,
        3,
        SAAS_COMMANDS,
        (("course",), ("lesson", "module"), ("enrollment", "student"), ("progress", "completion"), ("role", "permission")),
        True,
    ),
    "ai_chatbot_saas": CapabilityContract(
        8,
        300,
        3,
        SAAS_COMMANDS,
        (("chat", "conversation"), ("message",), ("model", "provider"), ("stream", "token"), ("jwt", "auth")),
        True,
    ),
    "complex_algorithm_service": CapabilityContract(
        4,
        220,
        3,
        ("python_test", "integration", "benchmark"),
        (("algorithm",), ("complexity",), ("benchmark",), ("validation", "edge case"), ("api", "endpoint")),
    ),
    "complex_3d_game": CapabilityContract(
        4,
        220,
        3,
        ("node_test", "build", "e2e"),
        (("three", "webgl"), ("requestanimationframe", "game loop"), ("score",), ("keyboard", "input"), ("collision", "physics")),
        True,
    ),
}


def evaluate_project_capability(scenario_id: str, summary: dict[str, Any]) -> dict[str, Any]:
    """Inspect project files and command artifacts instead of trusting summary labels."""

    contract = CONTRACTS.get(scenario_id)
    blockers: list[str] = []
    project_root = _project_root(summary)
    if contract is None:
        return _result(scenario_id, project_root, ["scenario_contract_missing"])
    if project_root is None or not project_root.is_dir():
        return _result(scenario_id, project_root, ["project_root_missing"])

    inventory = _inventory(project_root)
    if inventory["source_files"] < contract.minimum_source_files:
        blockers.append("insufficient_source_files")
    if inventory["meaningful_loc"] < contract.minimum_meaningful_loc:
        blockers.append("insufficient_meaningful_source")
    if inventory["test_files"] < contract.minimum_test_files:
        blockers.append("insufficient_test_files")
    if inventory["placeholder_source_files"]:
        blockers.append("placeholder_source_detected")

    corpus = inventory.pop("corpus")
    missing_keywords = ["|".join(group) for group in contract.keyword_groups if not any(word in corpus for word in group)]
    if missing_keywords:
        blockers.append("domain_contract_missing:" + ",".join(missing_keywords))

    verification = _verification(summary)
    command_kinds = _command_kinds(verification.get("commands_executed", []))
    if verification.get("status") != "PASSED":
        blockers.append("verification_not_passed")
    exit_codes = verification.get("exit_codes")
    if not isinstance(exit_codes, list) or not exit_codes or any(code != 0 for code in exit_codes):
        blockers.append("verification_exit_codes_invalid")
    for required in contract.required_command_kinds:
        if required not in command_kinds:
            blockers.append(f"verification_command_missing:{required}")
    if not _logs_exist(verification):
        blockers.append("verification_logs_missing")

    security = _evidence_document(summary, ("security_review.json", "security_report.json"))
    if not _security_passed(security):
        blockers.append("independent_security_review_missing")

    functional = _evidence_document(summary, ("functional_smoke.json",))
    if not _functional_smoke_passed(functional):
        blockers.append("functional_smoke_missing")

    visual = _visual_evidence(functional)
    if contract.requires_visual_evidence and not visual:
        blockers.append("visual_evidence_missing")

    return {
        **_result(scenario_id, project_root, blockers),
        "inventory": inventory,
        "command_kinds": sorted(command_kinds),
        "security_status": security.get("status", "MISSING"),
        "functional_smoke_status": functional.get("status", "MISSING"),
        "visual_evidence": visual,
        "contract": {
            "minimum_source_files": contract.minimum_source_files,
            "minimum_meaningful_loc": contract.minimum_meaningful_loc,
            "minimum_test_files": contract.minimum_test_files,
            "required_command_kinds": list(contract.required_command_kinds),
        },
    }


def _project_root(summary: dict[str, Any]) -> Path | None:
    raw = str(summary.get("project_root") or "").strip()
    if not raw:
        return None
    return Path(raw).resolve()


def _inventory(root: Path) -> dict[str, Any]:
    source_files = 0
    meaningful_loc = 0
    test_files = 0
    placeholders: list[str] = []
    corpus_parts: list[str] = []
    files_hashed = 0
    for path in root.rglob("*"):
        if not path.is_file() or any(part.lower() in EXCLUDED_PARTS for part in path.relative_to(root).parts):
            continue
        relative = path.relative_to(root).as_posix()
        if path.stat().st_size > 2_000_000:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        corpus_parts.extend((relative.lower(), text.lower()))
        files_hashed += 1
        if _is_test_file(relative):
            test_files += 1
        if path.suffix.lower() not in SOURCE_EXTENSIONS or _is_test_file(relative):
            continue
        source_files += 1
        lowered = text.lower()
        if any(marker in lowered for marker in PLACEHOLDER_MARKERS):
            placeholders.append(relative)
        meaningful_loc += sum(1 for line in text.splitlines() if _meaningful_line(line))
    return {
        "files_inspected": files_hashed,
        "source_files": source_files,
        "meaningful_loc": meaningful_loc,
        "test_files": test_files,
        "placeholder_source_files": placeholders,
        "corpus": "\n".join(corpus_parts),
    }


def _meaningful_line(line: str) -> bool:
    value = line.strip()
    return bool(value) and not value.startswith(("#", "//", "/*", "*", "--"))


def _is_test_file(relative: str) -> bool:
    lowered = relative.lower()
    name = Path(lowered).name
    return "test" in Path(lowered).parts or name.startswith("test_") or any(token in name for token in (".test.", ".spec."))


def _verification(summary: dict[str, Any]) -> dict[str, Any]:
    for artifact in reversed(_artifact_paths(summary)):
        if artifact.name == "47_project_verification.json" and artifact.is_file():
            return _read_json(artifact)
    return {}


def _command_kinds(commands: Any) -> set[str]:
    kinds: set[str] = set()
    if not isinstance(commands, list):
        return kinds
    for command in commands:
        if not isinstance(command, list):
            continue
        joined = " ".join(str(part).lower() for part in command)
        if "pytest" in joined:
            kinds.add("python_test")
        if any(tool in joined for tool in ("npm test", "npm run test", "pnpm test", "vitest", "node --test")) or (
            joined.startswith("npm --prefix ") and joined.endswith(" test")
        ):
            kinds.add("node_test")
        if any(token in joined for token in (" run build", "npm build", "vite build", "next build", "tsc --noemit")):
            kinds.add("build")
        if any(token in joined for token in ("playwright", " e2e", "integration")):
            kinds.add("e2e")
            kinds.add("integration")
        if "benchmark" in joined:
            kinds.add("benchmark")
    return kinds


def _logs_exist(verification: dict[str, Any]) -> bool:
    stdout = verification.get("stdout_artifacts")
    if not isinstance(stdout, list) or not stdout:
        return False
    return all(Path(str(path)).is_file() and Path(str(path)).stat().st_size > 0 for path in stdout)


def _evidence_document(summary: dict[str, Any], names: tuple[str, ...]) -> dict[str, Any]:
    for artifact in reversed(_artifact_paths(summary)):
        if artifact.name in names and artifact.is_file():
            return _read_json(artifact)
    project_root = _project_root(summary)
    if project_root:
        for name in names:
            matches = sorted(project_root.glob(f"**/{name}"))
            if matches:
                return _read_json(matches[-1])
    return {}


def _security_passed(payload: dict[str, Any]) -> bool:
    findings = payload.get("findings", [])
    if not isinstance(findings, list):
        return False
    severe = [item for item in findings if isinstance(item, dict) and str(item.get("severity", "")).upper() in {"HIGH", "CRITICAL"}]
    scanners = payload.get("scanners")
    return payload.get("status") == "PASSED" and isinstance(scanners, list) and bool(scanners) and not severe


def _functional_smoke_passed(payload: dict[str, Any]) -> bool:
    checks = payload.get("checks")
    return payload.get("status") == "PASSED" and isinstance(checks, list) and len(checks) >= 3 and all(
        isinstance(item, dict) and item.get("passed") is True for item in checks
    )


def _visual_evidence(payload: dict[str, Any]) -> list[str]:
    screenshots = payload.get("screenshots")
    if not isinstance(screenshots, list):
        return []
    return [str(path) for path in screenshots if Path(str(path)).is_file() and Path(str(path)).stat().st_size >= 100]


def _artifact_paths(summary: dict[str, Any]) -> list[Path]:
    artifacts = summary.get("artifacts")
    if not isinstance(artifacts, list):
        return []
    return [Path(str(path)) for path in artifacts if str(path).strip()]


def _read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _result(scenario_id: str, project_root: Path | None, blockers: list[str]) -> dict[str, Any]:
    return {
        "status": "CAPABILITY_VERIFIED" if not blockers else "CAPABILITY_BLOCKED",
        "passed": not blockers,
        "scenario_id": scenario_id,
        "project_root": str(project_root) if project_root else "",
        "blockers": blockers,
        "self_declared_summary_is_not_evidence": True,
    }
